# Generated by Django 4.2.11 on 2024-05-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='designation',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='email_address',
            new_name='scientific_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='phone_number',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='first_name',
            new_name='use',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='cost',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
